package auth

import "strings"

type PermissionService struct {
	rolePermissions map[string]map[string]struct{}
}

func NewPermissionService() *PermissionService {
	return &PermissionService{
		rolePermissions: map[string]map[string]struct{}{
			"platform-admin": {
				"*": {},
			},
			"ops-operator": {
				"resource:read":                    {},
				"operation:execute":                {},
				"observability:read":               {},
				"observability:write":              {},
				"workloadops:read":                 {},
				"workloadops:execute":              {},
				"workloadops:terminal":             {},
				"workloadops:rollback":             {},
				"workloadops:batch":                {},
				"gitops:read":                      {},
				"gitops:manage-source":             {},
				"gitops:sync":                      {},
				"gitops:promote":                   {},
				"gitops:rollback":                  {},
				"gitops:override":                  {},
				"securitypolicy:read":              {},
				"securitypolicy:manage":            {},
				"securitypolicy:enforce":           {},
				"compliance:read":                  {},
				"compliance:manage-baseline":       {},
				"compliance:execute-scan":          {},
				"compliance:manage-remediation":    {},
				"compliance:review-exception":      {},
				"compliance:export-archive":        {},
				"clusterlifecycle:read":            {},
				"clusterlifecycle:import":          {},
				"clusterlifecycle:create":          {},
				"clusterlifecycle:upgrade":         {},
				"clusterlifecycle:manage-nodepool": {},
				"clusterlifecycle:retire":          {},
				"clusterlifecycle:manage-driver":   {},
				"backuprestore:read":               {},
				"backuprestore:manage-policy":      {},
				"backuprestore:backup":             {},
				"backuprestore:restore":            {},
				"backuprestore:migrate":            {},
				"backuprestore:drill":              {},
				"identity:read":                    {},
				"identity:manage-source":           {},
				"identity:manage-org":              {},
				"identity:manage-role":             {},
				"identity:delegate":                {},
				"identity:session-govern":          {},
				"marketplace:read":                 {},
				"marketplace:manage-source":        {},
				"marketplace:publish-template":     {},
				"marketplace:manage-extension":     {},
			},
			"auditor": {
				"audit:read":                {},
				"gitops:read":               {},
				"securitypolicy:read":       {},
				"compliance:read":           {},
				"compliance:export-archive": {},
				"clusterlifecycle:read":     {},
				"backuprestore:read":        {},
				"identity:read":             {},
				"marketplace:read":          {},
			},
			"audit-reader": {
				"audit:read":                {},
				"observability:read":        {},
				"workloadops:read":          {},
				"gitops:read":               {},
				"securitypolicy:read":       {},
				"compliance:read":           {},
				"compliance:export-archive": {},
				"clusterlifecycle:read":     {},
				"backuprestore:read":        {},
			},
			"operator": {
				"resource:read":                    {},
				"operation:execute":                {},
				"observability:read":               {},
				"observability:write":              {},
				"workloadops:read":                 {},
				"workloadops:execute":              {},
				"workloadops:terminal":             {},
				"workloadops:rollback":             {},
				"workloadops:batch":                {},
				"gitops:read":                      {},
				"gitops:manage-source":             {},
				"gitops:sync":                      {},
				"gitops:promote":                   {},
				"gitops:rollback":                  {},
				"gitops:override":                  {},
				"securitypolicy:read":              {},
				"securitypolicy:manage":            {},
				"securitypolicy:enforce":           {},
				"compliance:read":                  {},
				"compliance:manage-baseline":       {},
				"compliance:execute-scan":          {},
				"compliance:manage-remediation":    {},
				"compliance:review-exception":      {},
				"compliance:export-archive":        {},
				"clusterlifecycle:read":            {},
				"clusterlifecycle:import":          {},
				"clusterlifecycle:create":          {},
				"clusterlifecycle:upgrade":         {},
				"clusterlifecycle:manage-nodepool": {},
				"clusterlifecycle:retire":          {},
				"clusterlifecycle:manage-driver":   {},
				"backuprestore:read":               {},
				"backuprestore:manage-policy":      {},
				"backuprestore:backup":             {},
				"backuprestore:restore":            {},
				"backuprestore:migrate":            {},
				"backuprestore:drill":              {},
				"identity:read":                    {},
				"identity:manage-source":           {},
				"identity:manage-org":              {},
				"identity:manage-role":             {},
				"identity:delegate":                {},
				"identity:session-govern":          {},
				"marketplace:read":                 {},
				"marketplace:manage-source":        {},
				"marketplace:publish-template":     {},
				"marketplace:manage-extension":     {},
			},
			"readonly": {
				"resource:read":             {},
				"audit:read":                {},
				"observability:read":        {},
				"workloadops:read":          {},
				"gitops:read":               {},
				"securitypolicy:read":       {},
				"compliance:read":           {},
				"compliance:export-archive": {},
				"clusterlifecycle:read":     {},
				"backuprestore:read":        {},
				"identity:read":             {},
				"marketplace:read":          {},
			},
			"workspace-owner": {
				"access:workspace:read":            {},
				"access:workspace:write":           {},
				"access:project:read":              {},
				"access:project:write":             {},
				"access:binding:read":              {},
				"access:binding:write":             {},
				"observability:read":               {},
				"observability:write":              {},
				"workloadops:read":                 {},
				"workloadops:execute":              {},
				"workloadops:terminal":             {},
				"workloadops:rollback":             {},
				"workloadops:batch":                {},
				"gitops:read":                      {},
				"gitops:manage-source":             {},
				"gitops:sync":                      {},
				"gitops:promote":                   {},
				"gitops:rollback":                  {},
				"gitops:override":                  {},
				"securitypolicy:read":              {},
				"securitypolicy:manage":            {},
				"securitypolicy:enforce":           {},
				"compliance:read":                  {},
				"compliance:manage-baseline":       {},
				"compliance:execute-scan":          {},
				"compliance:manage-remediation":    {},
				"compliance:review-exception":      {},
				"compliance:export-archive":        {},
				"clusterlifecycle:read":            {},
				"clusterlifecycle:import":          {},
				"clusterlifecycle:create":          {},
				"clusterlifecycle:upgrade":         {},
				"clusterlifecycle:manage-nodepool": {},
				"clusterlifecycle:retire":          {},
				"clusterlifecycle:manage-driver":   {},
				"backuprestore:read":               {},
				"backuprestore:manage-policy":      {},
				"backuprestore:backup":             {},
				"backuprestore:restore":            {},
				"backuprestore:migrate":            {},
				"backuprestore:drill":              {},
				"identity:read":                    {},
				"identity:manage-org":              {},
				"identity:manage-role":             {},
				"identity:delegate":                {},
				"identity:session-govern":          {},
				"marketplace:read":                 {},
				"marketplace:manage-source":        {},
				"marketplace:publish-template":     {},
				"marketplace:manage-extension":     {},
			},
			"workspace-viewer": {
				"access:workspace:read": {},
				"access:project:read":   {},
				"access:binding:read":   {},
				"observability:read":    {},
				"workloadops:read":      {},
				"gitops:read":           {},
				"securitypolicy:read":   {},
				"backuprestore:read":    {},
				"identity:read":         {},
				"marketplace:read":      {},
			},
			"project-owner": {
				"access:project:read":              {},
				"access:project:write":             {},
				"access:binding:read":              {},
				"access:binding:write":             {},
				"observability:read":               {},
				"observability:write":              {},
				"workloadops:read":                 {},
				"workloadops:execute":              {},
				"workloadops:terminal":             {},
				"workloadops:rollback":             {},
				"workloadops:batch":                {},
				"gitops:read":                      {},
				"gitops:manage-source":             {},
				"gitops:sync":                      {},
				"gitops:promote":                   {},
				"gitops:rollback":                  {},
				"gitops:override":                  {},
				"securitypolicy:read":              {},
				"securitypolicy:manage":            {},
				"securitypolicy:enforce":           {},
				"compliance:read":                  {},
				"compliance:manage-baseline":       {},
				"compliance:execute-scan":          {},
				"compliance:manage-remediation":    {},
				"compliance:review-exception":      {},
				"compliance:export-archive":        {},
				"clusterlifecycle:read":            {},
				"clusterlifecycle:import":          {},
				"clusterlifecycle:create":          {},
				"clusterlifecycle:upgrade":         {},
				"clusterlifecycle:manage-nodepool": {},
				"clusterlifecycle:retire":          {},
				"clusterlifecycle:manage-driver":   {},
				"backuprestore:read":               {},
				"backuprestore:manage-policy":      {},
				"backuprestore:backup":             {},
				"backuprestore:restore":            {},
				"backuprestore:migrate":            {},
				"backuprestore:drill":              {},
				"identity:read":                    {},
				"identity:manage-role":             {},
				"identity:delegate":                {},
				"marketplace:read":                 {},
				"marketplace:publish-template":     {},
			},
			"project-viewer": {
				"access:project:read":       {},
				"access:binding:read":       {},
				"observability:read":        {},
				"workloadops:read":          {},
				"gitops:read":               {},
				"securitypolicy:read":       {},
				"compliance:read":           {},
				"compliance:export-archive": {},
				"clusterlifecycle:read":     {},
				"backuprestore:read":        {},
				"identity:read":             {},
				"marketplace:read":          {},
			},
		},
	}
}

func (s *PermissionService) HasPermission(roleNames []string, permission string) bool {
	for _, role := range roleNames {
		grants, ok := s.rolePermissions[strings.ToLower(role)]
		if !ok {
			continue
		}
		if _, ok = grants["*"]; ok {
			return true
		}
		if _, ok = grants[permission]; ok {
			return true
		}
	}
	return false
}
