-- 0005_workload_operations_core.sql
-- Core schema for 003 workload operations control plane.

ALTER TABLE operation_requests
  ADD COLUMN IF NOT EXISTS cluster_id BIGINT UNSIGNED NULL AFTER operator_id,
  ADD COLUMN IF NOT EXISTS workspace_id BIGINT UNSIGNED NULL AFTER cluster_id,
  ADD COLUMN IF NOT EXISTS project_id BIGINT UNSIGNED NULL AFTER workspace_id,
  ADD COLUMN IF NOT EXISTS namespace VARCHAR(255) NULL AFTER target_ref,
  ADD COLUMN IF NOT EXISTS resource_kind VARCHAR(64) NULL AFTER namespace,
  ADD COLUMN IF NOT EXISTS resource_name VARCHAR(255) NULL AFTER resource_kind,
  ADD COLUMN IF NOT EXISTS target_instance_ref VARCHAR(255) NULL AFTER resource_name,
  ADD COLUMN IF NOT EXISTS payload_json LONGTEXT NULL AFTER target_instance_ref,
  ADD COLUMN IF NOT EXISTS progress_message TEXT NULL AFTER status,
  ADD COLUMN IF NOT EXISTS failure_reason TEXT NULL AFTER result_message,
  ADD COLUMN IF NOT EXISTS started_at TIMESTAMP NULL AFTER failure_reason,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP NULL AFTER started_at,
  ADD COLUMN IF NOT EXISTS risk_confirmed TINYINT(1) NOT NULL DEFAULT 0 AFTER risk_level,
  ADD KEY idx_operations_cluster (cluster_id),
  ADD KEY idx_operations_workspace (workspace_id),
  ADD KEY idx_operations_project (project_id),
  ADD KEY idx_operations_namespace_kind_name (namespace, resource_kind, resource_name);

CREATE TABLE IF NOT EXISTS workload_action_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  request_id VARCHAR(64) NOT NULL UNIQUE,
  operator_id BIGINT UNSIGNED NOT NULL,
  cluster_id BIGINT UNSIGNED NOT NULL,
  workspace_id BIGINT UNSIGNED NULL,
  project_id BIGINT UNSIGNED NULL,
  namespace VARCHAR(255) NOT NULL,
  resource_kind VARCHAR(64) NOT NULL,
  resource_name VARCHAR(255) NOT NULL,
  target_instance_ref VARCHAR(255) NULL,
  action_type VARCHAR(64) NOT NULL,
  risk_level VARCHAR(32) NOT NULL,
  risk_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  status VARCHAR(32) NOT NULL,
  progress_message TEXT NULL,
  result_message TEXT NULL,
  failure_reason TEXT NULL,
  batch_id BIGINT UNSIGNED NULL,
  started_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_workload_actions_operator (operator_id),
  KEY idx_workload_actions_cluster (cluster_id),
  KEY idx_workload_actions_workspace (workspace_id),
  KEY idx_workload_actions_project (project_id),
  KEY idx_workload_actions_status (status),
  KEY idx_workload_actions_batch (batch_id),
  CONSTRAINT fk_workload_actions_cluster FOREIGN KEY (cluster_id) REFERENCES clusters(id),
  CONSTRAINT fk_workload_actions_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
  CONSTRAINT fk_workload_actions_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS workload_batch_tasks (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  request_id VARCHAR(64) NOT NULL UNIQUE,
  operator_id BIGINT UNSIGNED NOT NULL,
  action_type VARCHAR(64) NOT NULL,
  scope_snapshot_json LONGTEXT NULL,
  risk_level VARCHAR(32) NOT NULL,
  risk_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  total_targets INT NOT NULL DEFAULT 0,
  succeeded_targets INT NOT NULL DEFAULT 0,
  failed_targets INT NOT NULL DEFAULT 0,
  canceled_targets INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  progress_percent INT NOT NULL DEFAULT 0,
  started_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_workload_batch_operator (operator_id),
  KEY idx_workload_batch_status (status)
);

CREATE TABLE IF NOT EXISTS workload_batch_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  cluster_id BIGINT UNSIGNED NOT NULL,
  workspace_id BIGINT UNSIGNED NULL,
  project_id BIGINT UNSIGNED NULL,
  namespace VARCHAR(255) NOT NULL,
  resource_kind VARCHAR(64) NOT NULL,
  resource_name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  action_request_id BIGINT UNSIGNED NULL,
  failure_reason TEXT NULL,
  result_message TEXT NULL,
  started_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_workload_batch_items_batch (batch_id),
  KEY idx_workload_batch_items_cluster (cluster_id),
  KEY idx_workload_batch_items_workspace (workspace_id),
  KEY idx_workload_batch_items_project (project_id),
  KEY idx_workload_batch_items_status (status),
  KEY idx_workload_batch_items_action (action_request_id),
  CONSTRAINT fk_workload_batch_items_batch FOREIGN KEY (batch_id) REFERENCES workload_batch_tasks(id),
  CONSTRAINT fk_workload_batch_items_cluster FOREIGN KEY (cluster_id) REFERENCES clusters(id),
  CONSTRAINT fk_workload_batch_items_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
  CONSTRAINT fk_workload_batch_items_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_workload_batch_items_action FOREIGN KEY (action_request_id) REFERENCES workload_action_requests(id)
);

CREATE TABLE IF NOT EXISTS workload_terminal_sessions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  session_key VARCHAR(128) NOT NULL UNIQUE,
  operator_id BIGINT UNSIGNED NOT NULL,
  cluster_id BIGINT UNSIGNED NOT NULL,
  workspace_id BIGINT UNSIGNED NULL,
  project_id BIGINT UNSIGNED NULL,
  namespace VARCHAR(255) NOT NULL,
  pod_name VARCHAR(255) NOT NULL,
  container_name VARCHAR(255) NOT NULL,
  workload_kind VARCHAR(64) NULL,
  workload_name VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL,
  started_at TIMESTAMP NULL,
  ended_at TIMESTAMP NULL,
  duration_seconds INT NOT NULL DEFAULT 0,
  close_reason VARCHAR(255) NULL,
  client_metadata_json LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_workload_terminal_operator (operator_id),
  KEY idx_workload_terminal_cluster (cluster_id),
  KEY idx_workload_terminal_workspace (workspace_id),
  KEY idx_workload_terminal_project (project_id),
  KEY idx_workload_terminal_status (status),
  CONSTRAINT fk_workload_terminal_cluster FOREIGN KEY (cluster_id) REFERENCES clusters(id),
  CONSTRAINT fk_workload_terminal_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
  CONSTRAINT fk_workload_terminal_project FOREIGN KEY (project_id) REFERENCES projects(id)
);
