CREATE TABLE IF NOT EXISTS compliance_baselines (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  standard_type VARCHAR(32) NOT NULL,
  version VARCHAR(64) NOT NULL,
  description TEXT NULL,
  target_levels_json LONGTEXT NULL,
  rules_json LONGTEXT NULL,
  rule_count INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
