CREATE TABLE IF NOT EXISTS identity_sources (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL UNIQUE,
  source_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  login_mode VARCHAR(32) NOT NULL,
  scope_mode VARCHAR(48) NOT NULL,
  sync_state VARCHAR(32) NOT NULL,
  config_summary TEXT NULL,
  last_error TEXT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  last_checked_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS identity_accounts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  identity_source_id BIGINT UNSIGNED NOT NULL,
  external_ref VARCHAR(190) NOT NULL,
  principal_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_identity_account_ref (identity_source_id, external_ref)
);

CREATE TABLE IF NOT EXISTS organization_units (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  unit_type VARCHAR(32) NOT NULL,
  name VARCHAR(128) NOT NULL,
  description TEXT NULL,
  parent_unit_id BIGINT UNSIGNED NULL,
  identity_source_id BIGINT UNSIGNED NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_org_unit_parent_name (parent_unit_id, name)
);

CREATE TABLE IF NOT EXISTS organization_memberships (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  unit_id BIGINT UNSIGNED NOT NULL,
  member_type VARCHAR(32) NOT NULL,
  member_ref VARCHAR(190) NOT NULL,
  membership_role VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  joined_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_org_membership_active (unit_id, member_type, member_ref, status)
);

CREATE TABLE IF NOT EXISTS tenant_scope_mappings (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  unit_id BIGINT UNSIGNED NOT NULL,
  scope_type VARCHAR(32) NOT NULL,
  scope_ref VARCHAR(190) NOT NULL,
  inheritance_mode VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tenant_scope_mapping (unit_id, scope_type, scope_ref)
);

CREATE TABLE IF NOT EXISTS role_definitions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  role_level VARCHAR(32) NOT NULL,
  description TEXT NULL,
  permission_summary TEXT NOT NULL,
  inheritance_policy VARCHAR(32) NOT NULL,
  delegable TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_role_definition_level_name (role_level, name)
);

CREATE TABLE IF NOT EXISTS role_assignments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  subject_type VARCHAR(32) NOT NULL,
  subject_ref VARCHAR(190) NOT NULL,
  role_definition_id BIGINT UNSIGNED NOT NULL,
  scope_type VARCHAR(32) NOT NULL,
  scope_ref VARCHAR(190) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  delegation_grant_id BIGINT UNSIGNED NULL,
  valid_from DATETIME NOT NULL,
  valid_until DATETIME NULL,
  status VARCHAR(32) NOT NULL,
  granted_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS delegation_grants (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  grantor_ref VARCHAR(190) NOT NULL,
  delegate_ref VARCHAR(190) NOT NULL,
  allowed_role_levels TEXT NOT NULL,
  allowed_scope_snapshot TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  valid_from DATETIME NOT NULL,
  valid_until DATETIME NOT NULL,
  reason TEXT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS identity_session_records (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  identity_source_id BIGINT UNSIGNED NOT NULL,
  login_method VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  risk_level VARCHAR(32) NOT NULL,
  permission_version VARCHAR(64) NOT NULL,
  last_seen_at DATETIME NULL,
  revoked_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS access_risk_snapshots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  subject_type VARCHAR(32) NOT NULL,
  subject_ref VARCHAR(190) NOT NULL,
  risk_type VARCHAR(64) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  summary TEXT NOT NULL,
  recommended_action TEXT NULL,
  status VARCHAR(32) NOT NULL,
  generated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS identity_governance_audit_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  action VARCHAR(128) NOT NULL,
  actor_user_id BIGINT UNSIGNED NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_ref VARCHAR(190) NOT NULL,
  outcome VARCHAR(32) NOT NULL,
  detail_snapshot TEXT NULL,
  occurred_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
