CREATE TABLE IF NOT EXISTS sre_ha_policies (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_id BIGINT UNSIGNED NULL,
  name VARCHAR(128) NOT NULL,
  control_plane_scope VARCHAR(128) NOT NULL,
  deployment_mode VARCHAR(64) NOT NULL,
  replica_expectation INT NOT NULL DEFAULT 1,
  failover_trigger_policy TEXT NULL,
  failover_cooldown VARCHAR(64) NULL,
  takeover_status VARCHAR(64) NOT NULL,
  last_failover_at DATETIME NULL,
  last_recovery_result TEXT NULL,
  status VARCHAR(32) NOT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_ha_workspace (workspace_id),
  KEY idx_sre_ha_project (project_id),
  KEY idx_sre_ha_status (status)
);

CREATE TABLE IF NOT EXISTS sre_maintenance_windows (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_id BIGINT UNSIGNED NULL,
  name VARCHAR(128) NOT NULL,
  window_type VARCHAR(64) NOT NULL,
  scope VARCHAR(128) NOT NULL,
  start_at DATETIME NOT NULL,
  end_at DATETIME NOT NULL,
  allowed_operations TEXT NULL,
  restricted_operations TEXT NULL,
  status VARCHAR(32) NOT NULL,
  exception_reason TEXT NULL,
  approval_record TEXT NULL,
  post_check_status VARCHAR(64) NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_window_workspace (workspace_id),
  KEY idx_sre_window_project (project_id),
  KEY idx_sre_window_status (status)
);

CREATE TABLE IF NOT EXISTS sre_platform_health_snapshots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_id BIGINT UNSIGNED NULL,
  ha_policy_id BIGINT UNSIGNED NULL,
  snapshot_at DATETIME NOT NULL,
  component_health_summary TEXT NULL,
  dependency_health_summary TEXT NULL,
  task_backlog_summary TEXT NULL,
  capacity_risk_level VARCHAR(32) NOT NULL,
  throttling_status VARCHAR(64) NOT NULL,
  recovery_summary TEXT NULL,
  maintenance_status VARCHAR(64) NOT NULL,
  overall_status VARCHAR(32) NOT NULL,
  recommended_actions TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_health_workspace (workspace_id),
  KEY idx_sre_health_project (project_id),
  KEY idx_sre_health_snapshot (snapshot_at)
);

CREATE TABLE IF NOT EXISTS sre_capacity_baselines (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_id BIGINT UNSIGNED NULL,
  name VARCHAR(128) NOT NULL,
  resource_dimension VARCHAR(64) NOT NULL,
  baseline_range TEXT NULL,
  thresholds TEXT NULL,
  growth_trend TEXT NULL,
  forecast_window VARCHAR(64) NOT NULL,
  forecast_result TEXT NULL,
  confidence_level VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_capacity_workspace (workspace_id),
  KEY idx_sre_capacity_project (project_id),
  KEY idx_sre_capacity_status (status)
);

CREATE TABLE IF NOT EXISTS sre_upgrade_plans (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_id BIGINT UNSIGNED NULL,
  maintenance_window_id BIGINT UNSIGNED NULL,
  name VARCHAR(128) NOT NULL,
  current_version VARCHAR(64) NOT NULL,
  target_version VARCHAR(64) NOT NULL,
  compatibility_summary TEXT NULL,
  precheck_result TEXT NULL,
  rollout_strategy TEXT NULL,
  execution_stage VARCHAR(64) NOT NULL,
  execution_progress INT NOT NULL DEFAULT 0,
  acceptance_result TEXT NULL,
  rollback_readiness TEXT NULL,
  status VARCHAR(32) NOT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_upgrade_workspace (workspace_id),
  KEY idx_sre_upgrade_project (project_id),
  KEY idx_sre_upgrade_status (status)
);

CREATE TABLE IF NOT EXISTS sre_rollback_validations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  upgrade_plan_id BIGINT UNSIGNED NOT NULL,
  validation_scope VARCHAR(128) NOT NULL,
  preconditions TEXT NULL,
  result VARCHAR(32) NOT NULL,
  remaining_risk TEXT NULL,
  validated_at DATETIME NOT NULL,
  validated_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_rollback_plan (upgrade_plan_id),
  KEY idx_sre_rollback_result (result)
);

CREATE TABLE IF NOT EXISTS sre_runbook_articles (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_id BIGINT UNSIGNED NULL,
  title VARCHAR(128) NOT NULL,
  scenario_type VARCHAR(64) NOT NULL,
  applicable_components TEXT NULL,
  risk_level VARCHAR(32) NOT NULL,
  checklist_summary TEXT NULL,
  recovery_steps TEXT NULL,
  verification_summary TEXT NULL,
  status VARCHAR(32) NOT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_runbook_workspace (workspace_id),
  KEY idx_sre_runbook_project (project_id),
  KEY idx_sre_runbook_status (status)
);

CREATE TABLE IF NOT EXISTS sre_alert_baselines (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_id BIGINT UNSIGNED NULL,
  name VARCHAR(128) NOT NULL,
  component_scope VARCHAR(128) NOT NULL,
  signal_type VARCHAR(64) NOT NULL,
  baseline_condition TEXT NULL,
  severity VARCHAR(32) NOT NULL,
  recommended_runbook_id BIGINT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_alert_workspace (workspace_id),
  KEY idx_sre_alert_project (project_id),
  KEY idx_sre_alert_status (status)
);

CREATE TABLE IF NOT EXISTS sre_scale_evidence (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_id BIGINT UNSIGNED NULL,
  capacity_baseline_id BIGINT UNSIGNED NULL,
  runbook_article_id BIGINT UNSIGNED NULL,
  evidence_type VARCHAR(64) NOT NULL,
  scope VARCHAR(128) NOT NULL,
  sample_window VARCHAR(64) NOT NULL,
  summary TEXT NULL,
  bottleneck_summary TEXT NULL,
  forecast_summary TEXT NULL,
  confidence_level VARCHAR(32) NOT NULL,
  recovery_observation TEXT NULL,
  status VARCHAR(32) NOT NULL,
  captured_at DATETIME NOT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sre_evidence_workspace (workspace_id),
  KEY idx_sre_evidence_project (project_id),
  KEY idx_sre_evidence_type (evidence_type),
  KEY idx_sre_evidence_status (status)
);
