import '@testing-library/jest-dom/vitest';
import { render, screen } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
import { ScanCenterPage } from '@/features/compliance-hardening/pages/ScanCenterPage';
import { useAuthStore } from '@/features/auth/store';
import { listScanExecutions, listScanProfiles } from '@/services/compliance';
import { installAntdDomShims } from '@/test/installAntdDomShims';
vi.mock('@/services/compliance', async () => ({ ...(await vi.importActual<typeof import('@/services/compliance')>('@/services/compliance')), listScanProfiles: vi.fn(), listScanExecutions: vi.fn(), executeScanProfile: vi.fn() }));
const renderPage = () => render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><MemoryRouter><ScanCenterPage /></MemoryRouter></QueryClientProvider>);
describe('ScanCenterPage', () => { beforeAll(() => installAntdDomShims()); beforeEach(() => { vi.clearAllMocks(); vi.mocked(listScanProfiles).mockResolvedValue({ items: [] }); vi.mocked(listScanExecutions).mockResolvedValue({ items: [] }); }); it('shows unauthorized empty', () => { useAuthStore.setState({ isAuthenticated: true, accessToken: 't', refreshToken: 'r', user: { id: 'u', username: 'u', platformRoles: [] } }); renderPage(); expect(screen.getByText('你暂无合规扫描访问权限。')).toBeInTheDocument(); }); it('renders scan tables', async () => { useAuthStore.setState({ isAuthenticated: true, accessToken: 't', refreshToken: 'r', user: { id: 'u', username: 'u', platformRoles: ['platform-admin'] } }); vi.mocked(listScanProfiles).mockResolvedValue({ items: [{ id: 'p1', name: 'daily', baselineId: 'b1', scopeType: 'cluster', scheduleMode: 'manual', clusterRefs: ['1'], status: 'active' }] }); vi.mocked(listScanExecutions).mockResolvedValue({ items: [{ id: 's1', score: 80, status: 'succeeded', coverageStatus: 'full' }] }); renderPage(); expect(await screen.findByText('daily')).toBeInTheDocument(); expect(await screen.findByText('s1')).toBeInTheDocument(); }); });
